name: cost_snap
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  animated_text_kit: ^4.2.3
  archive: ^4.0.7
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3

  flutter_native_splash: ^2.4.5
  flutter_spinkit: ^5.2.1
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  ionicons: ^0.2.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/coin_roll.json
    - assets/animations/cost.json

flutter_native_splash:
  color: "#007AFF" # Background color (hex code)
  android: true # Enable for Android
  ios: true # Enable for iOS

flutter_launcher_icons:
  android: true # Generate for Android
  ios: true # Generate for iOS
  image_path: "assets/images/icon.png" # Path to your icon
  min_sdk_android: 21 # Minimum Android SDK (optional)
